name: Trivy smoke tests
on:
  workflow_dispatch:
    inputs:
      log_level:
        required: true
        type: choice
        options:
        - INFO
        - DEBUG
        - TRACE
      dev_registry_branch: 
        type: string
        default: main
        description: >-
          Which branch of boostsecurityio/dev-registry to use in dev
        
env:
  BOOST_LOG_LEVEL: ${{ inputs.log_level }}

jobs:
  boost:
    name: Trivy on ${{ matrix.target }} to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [gitleaks, osv-scanner, rclone, kubeaudit]
        environment: [prod, dev]
        include:
          - environment: prod
            registry_url: https://github.com/boost-community/scanner-registry.git
            api_endpoint: https://api.boostsecurity.io
            api_token_secret_name: BOOST_API_KEY
          - environment: dev
            registry_url: https://github.com/boostsecurityio/dev-registry.git#${{inputs.dev_registry_branch}}
            api_endpoint: https://api.dev.boostsec.io
            api_token_secret_name: BOOST_API_KEY_DEV
    steps:
      - name: Clone
        uses: actions/checkout@v3
      
      - name: 'trivy-fs on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-fs
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }}
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
          
      - name: 'trivy-sbom on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-sbom
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }}
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
    
      - name: 'boost-sca on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/boost-sca
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }}
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
          
      - name: Prepare Docker image
        env:
          BOOST_IMAGE_NAME: ${{ matrix.target }}
        run: |
          cd "$BOOST_IMAGE_NAME"
          docker build -t "$BOOST_IMAGE_NAME" .
          
      - name: 'trivy-image on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-image
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }} Docker
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
          BOOST_IMAGE_NAME: ${{ matrix.target }}

      - name: 'trivy-sbom-image on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-sbom-image
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }} Docker
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
          BOOST_IMAGE_NAME: ${{ matrix.target }}
