name: Trivy smoke tests
on:
  workflow_dispatch:
  push:
  
env:
  BOOST_LOG_LEVEL: INFO

jobs:
  boost:
    name: Trivy on ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - gitleaks
        - osv-scanner
        - rclone
        include:
          - registry_url: https://github.com/boost-community/scanner-registry.git
            api_endpoint: https://api.boostsecurity.io
            api_token_secret_name: BOOST_API_KEY
          - registry_url: https://github.com/boostsecurityio/dev-registry.git#BST-5714_01_update_trivy
            api_endpoint: https://api.dev.boostsec.io
            api_token_secret_name: BOOST_API_KEY_DEV
    steps:
      - name: Clone
        uses: actions/checkout@v3
      
      - name: 'trivy-fs on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-fs
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }}
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
          
      - name: 'trivy-sbom on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-sbom
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }}
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}

      - name: Prepare Docker image
        env:
          BOOST_IMAGE_NAME: ${{ matrix.target }}
        run: |
          cd "$BOOST_IMAGE_NAME"
          docker build -t "$BOOST_IMAGE_NAME" .
          
      - name: 'trivy-image on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-image
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }}
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
          BOOST_IMAGE_NAME: ${{ matrix.target }}

      - name: 'trivy-sbom-image on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-sbom-image
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }}
          scan_path: ${{ matrix.target }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
          BOOST_IMAGE_NAME: ${{ matrix.target }}
