name: boostsecurity.io
on:
  workflow_dispatch:
  push:

jobs:
  boost:
    name: SAST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
        - gitleaks
#         - osv-scanner
#         - rclone

    steps:
      - id: submodule
        env:
          API_URL: "/repos/${{ github.repository }}/contents/${{ matrix.image }}"
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api "$API_URL" | jq -r '{"SHA": .sha, "REPO": .submodule_git_url | sub("https://github.com/"; "") | sub(".git$"; "")} | to_entries[] | join("=")' >> $GITHUB_OUTPUT

      - name: Clone
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.submodule.outputs.REPO  }}
          ref: ${{ steps.submodule.outputs.SHA  }}

      - env:
          BOOST_IMAGE_NAME: ${{ matrix.image }}
        run: |
          docker build -t "$BOOST_IMAGE_NAME" .

      - name: 'trivy-fs on ${{ matrix.image }}'
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          BOOST_IMAGE_NAME: ${{ matrix.image }}
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/trivy-fs
          api_endpoint: https://api.dev.boostsec.io
          additional_args: --registry https://github.com/boostsecurityio/scanner-testing.git#add-trivy-fs --path $GITHUB_WORKSPACE/$BOOST_IMAGE_NAME
          log_level: DEBUG
          scan_label: ${{ matrix.image }}

      - name: 'trivy-sbom on ${{ matrix.image }}'
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/trivy-sbom
          api_endpoint: https://api.dev.boostsec.io
          additional_args: --registry https://github.com/boostsecurityio/scanner-testing.git --path $GITHUB_WORKSPACE/$BOOST_IMAGE_NAME
          log_level: DEBUG
          scan_label: ${{ matrix.image }}
          scan_path: ${{ matrix.image }}

      - name: 'trivy-image on ${{ matrix.image }}'
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          BOOST_IMAGE_NAME: ${{ matrix.image }}
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/trivy-image
          api_endpoint: https://api.dev.boostsec.io
          additional_args: --registry https://github.com/boostsecurityio/scanner-testing.git
          log_level: DEBUG
          scan_label: ${{ matrix.image }}
          scan_path: ${{ matrix.image }}

      - name: 'trivy-sbom-image on ${{ matrix.image }}'
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          BOOST_IMAGE_NAME: ${{ matrix.image }}
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/trivy-sbom-image
          api_endpoint: https://api.dev.boostsec.io
          additional_args: --registry https://github.com/boostsecurityio/scanner-testing.git
          log_level: DEBUG
          scan_label: ${{ matrix.image }}
          scan_path: ${{ matrix.image }}
